- hosts: all
  tasks:
  - debug: var=lul_var
  - name: print ip url
    debug:
      msg: "This might be the public ip {{ manageiq.api_url }}"
  #- name: print event target
    #debug:
      #msg: "This might be the event target {{ manageiq.event_target }}"
  - debug: var=omar_var
  - name: print vm id
    debug:
      msg: "This might be the vm id {{ vmid }}"
  - name: print vm name
    debug:
      msg: "This might be the vm name {{ vmname }}"
  - name: Ansible create file if it doesn't exist example
    file:
      path: "~/omar.txt"
      state: touch
