- hosts: all
  tasks:
  - name: print ip address
    debug:
      msg: "This might be the public ip {{ omar_var }}"
  - name: print ip address again
    debug:
      msg: "This might be the public ip {{ miq_provision.destination.floating_ip_addresses.first }}"
  - name: Ansible create file if it doesn't exist example
    file:
      path: "~/omar.txt"
      state: touch
